name: 'Telegram Send Docker Build Action'
description: 'Send a message with docker image info, commit & trigger data'
inputs:
  bot-key:
    required: true
    descrpition: 'telegram bot credentials'
  chat-id:
      required: true
      descrpition: 'telegram target chat id'
  event:
    required: true
    descrpition: 'an event which triggered an artifact build to specify in a message'
  source:
    required: true
    descrpition: 'repository which produced atrifacts name to specify in a messaage'
  ref:
    required: true
    descrpition: 'branch or tag value to specify in a message'
  docker-image:
    required: true
    descrpition: 'docker image with tag (e.g. org/image:tag) to specify in a message'
  commit-hash:
    required: true
    descrpition: 'commit hash which produces atrifacts to specify in a message'
  commit-message:
    required: false
    descrpition: 'commit message to specify'
outputs:
  empty: # id of output
    description: 'empty output'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --bot-key
    - ${{ inputs.bot-key }}
    - --chat-id
    - ${{ inputs.chat-id }}
    - --event
    - ${{ inputs.event }}
    - --source
    - ${{ inputs.source }}
    - --ref
    - ${{ inputs.ref }}
    - --docker-image
    - ${{ inputs.docker-image }}
    - --commit-hash
    - ${{ inputs.commit-hash }}
    - --commit-message
    - ${{ inputs.commit-message }}
